name: tutelar_pet_app
description: Tutelar Pet - Auxiliando nos cuidados e proteção do seu Pet.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0-290.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.12.0"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/home.png
    - lib/assets/images/avatar.png
    - lib/assets/images/drawer.png
    - lib/assets/images/tutelarPet.png

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "lib/assets/images/tutelarPet.png"
